TICK_PRICE_FIELD = 'Price'
TICK_VOLUME_FIELD = 'Size'
OPEN, HIGH, LOW, CLOSE = 'open', 'high', 'low', 'close'
VOLUME, TRADES, VWAP = 'volume', 'trades', 'vwap'
NAN, NON_POSTIVE, OUTLIER = 'nan', 'non_positive', 'outlier'